---
title: "PSCI3200 Final Project"
institute: "University of Pennsylvania"
#class: "PSCI3200: Global Development - Intermediate Topics in Politics, Policy, and Data
#quarto render "PSCI3200 Final Project.qmd"
---

All of the data and scripts for this assignment can be found at https://github.com/Glucier39/PSCI3200_Final

# Introduction

Over the past two decades, China has rapidly emerged as a dominant financial actor in Africa, reshaping the development landscape of the continent’s most resource-rich states through infrastructure loans. Despite their abundant natural resource endowments, they often fail to achieve inclusive and sustained economic progress. Known as the resource curse or the “paradox of plenty”, resource curse literature posits that “countries with large endowments of natural resources, such as oil and gas, often perform worse in terms of economic development and governance than do countries with fewer resources,” despite the “prospects of wealth and opportunity that accompany the discovery and extraction” (Soros, 2007). Consequently, the economic potential of resource wealth distorts governance incentives, enabling ruling elites to consolidate power, evade public accountability, and suppress institutional checks.

A critical factor reinforcing this dynamic in recent years has been the rise of Chinese development finance. Since 2000, “39 Chinese lenders provided 1,243 loans amounting to \$170.08 billion to 49 African governments and seven regional institutions” (Boston University Global Development Policy Center, 2023). A significant share of this financing has flowed to petrostates - countries whose economies are heavily dependent on the extraction and export of oil and natural gas (Sow, 2018). While these loans are typically dedicated towards infrastructure, there has been much debate over weather they should be categorized as productive or predatory. Still, analysis hold that infrastructure loans (especially for transport and communication sectors) are critical for reducing trade costs with that country and increasing participation in global value chains (Amendolagine et al., 2024). Across the board, however, oil states have emerged as the primary receiver of these loans.

As China's energy consumption grows, these exchanges have "taken the form of "loan-for-oil" deals, where Chinese state billions of dollars to oil-producing countries at below-market interest rates in exchange for the producers’ agreements to sell oil to Chinese oil companies (at future market prices rather than at a fixed price) (Gholz, 2017). Moreover, while these loans do not always directly fund resource extraction, they are collateralized by future resource revenues; a structure in which the borrowing country commits future earnings from oil or mineral exports to repay Chinese creditors (Usman, 2001). These oil-rich nations not only fit the profile of the resource curse but also increasingly rely on opaque, collateralized Chinese financing that lacks the transparency and governance conditions typically required by traditional lenders. Scholars such as Ross (2001) and Auty (1993) have shown how resource-rich governments often circumvent the need for taxation and public accountability by leveraging resource revenues to consolidate political control. When government spending is more dependent on citizen taxation, those same governments are more likely to democratize. In contrast, when governments rely heavily on resource rents (rather than citizen taxation) to fund the national budget, public oversight tends to diminish and allows elites greater freedom to divert funds for personal gain (National Resource Governance Institute, 2015). Consequently, less money is reinvested into infrastructure and country is forced to take out loans.

Most studies have prioritized the economic and developmental impacts of Chinese financing—such as debt sustainability and infrastructure outcomes—while giving less attention to its political consequences. This research paper expands pre-existing resource curse literature by examining the political impact of Chinese loans on oil-rich countries through the lens of executive corruption, filling a gap in the literature which has often studied and projected the economic consequences of Africa’s debt to China.

Scholars such as Ross (2015) and Dreher et al. (2018) further outline how resource revenues enable ruling elites to bypass institutional constraints, leading to weakened public accountability and entrenched autocracy. Political scientists typically find that, While the “resource curse” has been extensively studied in political economy literature, much of the focus has remained on how oil and mineral wealth distort governance incentives, weaken institutions, and enable authoritarian persistence. Scholars such as Ross (2001) and Auty (1993) have shown how resource-rich governments often circumvent the need for taxation and public accountability by leveraging resource revenues to consolidate political control. In parallel, a growing body of research has examined China’s expanding role as a global lender—particularly its large-scale financing of infrastructure projects across Africa. Studies from AidData and the Center for Global Development (e.g., Gelpern et al., 2021) have demonstrated that Chinese loans are often opaque, lack governance-related conditionality, and are frequently collateralized by future oil revenues. However, the existing literature remains limited in several key respects.
